functionsDirectory = "/Users/Mobarez_1/Acc-File-Invoice-main/backend/functions"
functionsDirectoryOrigin = "config"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]
node_bundler = "nft"
timeout = 26.0

[build]
publish = "/Users/Mobarez_1/Acc-File-Invoice-main/backend/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install --include=dev && npx prisma generate && mkdir -p dist"
functions = "/Users/Mobarez_1/Acc-File-Invoice-main/backend/functions"

[build.environment]
NODE_VERSION = "20.19.0"
NODE_ENV = "production"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept"
Access-Control-Allow-Credentials = "true"
Access-Control-Max-Age = "600"

[[headers]]
for = "/.netlify/functions/*"

[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept"
Access-Control-Allow-Credentials = "true"

[[redirects]]
from = "/*"
to = "/.netlify/functions/api/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]